"""initial archive schema

Revision ID: fc73750faf43
Revises: 
Create Date: 2026-07-23 14:16:00.772070
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fc73750faf43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_access_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archive_access_log_created_at'), 'archive_access_log', ['created_at'], unique=False)
    op.create_table('archived_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sms_body', sa.Text(), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_html_body', sa.Text(), nullable=True),
    sa.Column('email_plain_body', sa.Text(), nullable=True),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('sms_sender_id', sa.String(length=20), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('sms_sent', sa.Integer(), nullable=False),
    sa.Column('sms_failed', sa.Integer(), nullable=False),
    sa.Column('email_sent', sa.Integer(), nullable=False),
    sa.Column('email_failed', sa.Integer(), nullable=False),
    sa.Column('contact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('never_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_campaigns_account_id'), 'archived_campaigns', ['account_id'], unique=False)
    op.create_index(op.f('ix_archived_campaigns_archived_at'), 'archived_campaigns', ['archived_at'], unique=False)
    op.create_table('archived_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('amount_ugx', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('flutterwave_tx_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_payments_account_id'), 'archived_payments', ['account_id'], unique=False)
    op.create_table('archived_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=True),
    sa.Column('storage_class', sa.String(length=20), nullable=False),
    sa.Column('retrieval_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_to', sa.String(length=320), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_reports_account_id'), 'archived_reports', ['account_id'], unique=False)
    op.create_index(op.f('ix_archived_reports_campaign_id'), 'archived_reports', ['campaign_id'], unique=False)
    op.create_table('archived_source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('contact_list_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('storage_class', sa.String(length=20), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('upload_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_deleted', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_source_files_account_id'), 'archived_source_files', ['account_id'], unique=False)
    op.create_table('erasure_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('master_contact_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_by', sa.UUID(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_erasure_requests_status'), 'erasure_requests', ['status'], unique=False)
    op.create_table('legal_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('placed_by', sa.UUID(), nullable=True),
    sa.Column('placed_by_email', sa.String(length=320), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lifted_by', sa.UUID(), nullable=True),
    sa.Column('lifted_reason', sa.Text(), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_holds_is_active'), 'legal_holds', ['is_active'], unique=False)
    op.create_index(op.f('ix_legal_holds_resource_id'), 'legal_holds', ['resource_id'], unique=False)
    op.create_table('master_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_filename', sa.String(length=512), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('campaign_appearances', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anonymised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('never_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_contacts_account_id'), 'master_contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_master_contacts_email'), 'master_contacts', ['email'], unique=True)
    op.create_index(op.f('ix_master_contacts_phone'), 'master_contacts', ['phone'], unique=True)
    op.create_table('retention_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('retention_months', sa.Integer(), nullable=True),
    sa.Column('never_delete', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_rules_account_id'), 'retention_rules', ['account_id'], unique=False)
    op.create_index(op.f('ix_retention_rules_domain'), 'retention_rules', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_rules_domain'), table_name='retention_rules')
    op.drop_index(op.f('ix_retention_rules_account_id'), table_name='retention_rules')
    op.drop_table('retention_rules')
    op.drop_index(op.f('ix_master_contacts_phone'), table_name='master_contacts')
    op.drop_index(op.f('ix_master_contacts_email'), table_name='master_contacts')
    op.drop_index(op.f('ix_master_contacts_account_id'), table_name='master_contacts')
    op.drop_table('master_contacts')
    op.drop_index(op.f('ix_legal_holds_resource_id'), table_name='legal_holds')
    op.drop_index(op.f('ix_legal_holds_is_active'), table_name='legal_holds')
    op.drop_table('legal_holds')
    op.drop_index(op.f('ix_erasure_requests_status'), table_name='erasure_requests')
    op.drop_table('erasure_requests')
    op.drop_index(op.f('ix_archived_source_files_account_id'), table_name='archived_source_files')
    op.drop_table('archived_source_files')
    op.drop_index(op.f('ix_archived_reports_campaign_id'), table_name='archived_reports')
    op.drop_index(op.f('ix_archived_reports_account_id'), table_name='archived_reports')
    op.drop_table('archived_reports')
    op.drop_index(op.f('ix_archived_payments_account_id'), table_name='archived_payments')
    op.drop_table('archived_payments')
    op.drop_index(op.f('ix_archived_campaigns_archived_at'), table_name='archived_campaigns')
    op.drop_index(op.f('ix_archived_campaigns_account_id'), table_name='archived_campaigns')
    op.drop_table('archived_campaigns')
    op.drop_index(op.f('ix_archive_access_log_created_at'), table_name='archive_access_log')
    op.drop_table('archive_access_log')
    # ### end Alembic commands ###
