import type { Metadata } from "next";

/**
 * Central SEO configuration + metadata / JSON-LD builders.
 *
 * SITE_URL is the canonical public origin. It drives `metadataBase`, canonical
 * URLs, Open Graph URLs, the sitemap, and robots — so every absolute link the
 * crawlers see is consistent. Override per-environment with NEXT_PUBLIC_SITE_URL
 * (must be a full origin, no trailing slash needed — we strip it).
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://bulkreach.ug"
).replace(/\/+$/, "");

export const SITE_NAME = "BulkReach";

export const DEFAULT_TITLE = "BulkReach — Bulk SMS & Email for Uganda";

export const DEFAULT_DESCRIPTION =
  "Professional bulk SMS & email campaigns for Uganda's businesses — personalised merge tags, auto-generated PDF reports, and a fully managed option.";

export function absoluteUrl(path = "/"): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Default social-share image, generated by app/opengraph-image.tsx. We reference
 * it explicitly (rather than relying on the file-convention auto-injection),
 * because every page defines its own `openGraph` block — which shadows a
 * parent-segment opengraph-image file. Explicit keeps og:image on every page.
 */
export const OG_IMAGE = {
  url: absoluteUrl("/opengraph-image"),
  width: 1200,
  height: 630,
  alt: DEFAULT_TITLE,
};

interface PageMetaInput {
  /** Page title. Runs through the "%s · BulkReach" template unless titleAbsolute. */
  title: string;
  description: string;
  /** Canonical path for this page, e.g. "/pricing". */
  path: string;
  /** Use the title verbatim (no brand template) — for the home page. */
  titleAbsolute?: boolean;
}

/**
 * Build a complete, self-contained Metadata block for a public page: canonical
 * URL + Open Graph + Twitter. The default OG image is supplied automatically by
 * app/opengraph-image.tsx (Next injects it into every route's metadata), so we
 * never set `images` here.
 */
export function pageMetadata({
  title,
  description,
  path,
  titleAbsolute,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);
  const ogTitle = titleAbsolute ? title : `${title} · ${SITE_NAME}`;
  return {
    title: titleAbsolute ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: "en_UG",
      url,
      title: ogTitle,
      description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}

// ─── JSON-LD structured-data builders ───────────────────────────────────────
// Each returns a plain schema.org object rendered via <JsonLd/>. Kept minimal
// and truthful — only claims backed by real, on-page content.

export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    url: SITE_URL,
    logo: absoluteUrl("/icon.svg"),
    description: DEFAULT_DESCRIPTION,
    areaServed: "UG",
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      email: "support@bulkreach.ug",
    },
  };
}

export function websiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: SITE_URL,
  };
}

export function softwareApplicationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: SITE_NAME,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
    description: DEFAULT_DESCRIPTION,
    offers: {
      "@type": "Offer",
      priceCurrency: "UGX",
      description: "Free trial — 500 messages, no credit card required.",
    },
  };
}

export interface FaqLike {
  q: string;
  a: string;
}

export function faqSchema(faqs: FaqLike[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((f) => ({
      "@type": "Question",
      name: f.q,
      acceptedAnswer: { "@type": "Answer", text: f.a },
    })),
  };
}
